name: datalayer
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-packaging
  - jupyter-server-proxy
  - matplotlib
  - nodejs=14.15.1
  - pandas
  - pip
  - pycurl
  - pytest
  - python=3.9
  - twine
  - yarn=1.22.5
  - pip:
    - jupyterlab==3.1.0
    - jupyterlab-lsp
    - python-language-server[all]
